name: Continuos Integration

on:
  pull_request:
    branches:
      ['main', 'homolog', 'develop']

jobs:
  continuos_integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: './.github/.node-version'
          cache: 'npm'
      - name: run install, build and tests
        run: |
          npm install
          npm run build
          npm run test
